version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "=== Installing dependencies ==="
      - npm install
  build:
    commands:
      - echo "=== Generating Prisma Client ==="
      - npx prisma generate
      - echo "=== Building TypeScript ==="
      - npx tsc
      - echo "=== Running Prisma Migrate Deploy ==="
      - npx prisma migrate deploy
artifacts:
  files:
    - dist/**/*
    - prisma/**/*
    - package.json
    - package-lock.json
    - appspec.yml
    - scripts/**/*
